### ISSUE TITLE
Issue while importing cppyy  2..4.1 under python 3.7 - visual studio 2019 - windows 10

### ISSUE THREAD

**Issue by mboker001** [wlav/cppyy#117] opened 2022-12-17 19:40 UTC
I am trying to import CPPYY (version 2.4.1)  under a python 3.7 environment on windows 10 and visual studio 2019. when i run the command : 
 >>> import cppyy

i get the following error message. Any idea how to fix the issue
Many Thanks

C:\MyPyenv\venv3\lib\site-packages\cppyy_backend\loader.py:139: UserWarning: No precompiled header available (No module named 'cppyy_backend._version'); this may impact performance.
  warnings.warn('No precompiled header available (%s); this may impact performance.' % msg)
input_line_1:1:10: fatal error: 'new' file not found
#include <new>
         ^~~~~
Warning in cling::IncrementalParser::CheckABICompatibility():
  Failed to extract C++ standard library version.
Replaced symbol atexit cannot be found in JIT!
Replaced symbol at_quick_exit cannot be found in JIT!
Replaced symbol __dllonexit cannot be found in JIT!
Replaced symbol _onexit cannot be found in JIT!
In file included from input_line_3:1:
In file included from C:/MyPyenv/venv3/lib/site-packages/cppyy_backend\include\Rtypes.h:22:
In file included from C:/MyPyenv/venv3/lib/site-packages/cppyy_backend\include/RtypesCore.h:23:
In file included from C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\ucrt\stddef.h:12:
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\ucrt\corecrt.h:10:10: fatal error: 'vcruntime.h' file not found
#include <vcruntime.h>
         ^~~~~~~~~~~~~
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import

**Comment by wlav** [comment] 2022-12-17 19:48
Do you have MSVC installed and are you running python from an environment with MSVC setup?

**Comment by mboker001** [comment] 2022-12-17 19:53
Hi, thank you for your reply.
 i have the following full  C++ development setup installed :C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133

**Comment by mboker001** [comment] 2022-12-17 19:59
i am running python from a virtual environment. how can i check that MSVC is set up  in 
that environment?

**Comment by wlav** [comment] 2022-12-17 20:01
Easiest is probably to check whether the MSVC command line tools are available., eg. `cl.exe` through the `PATH` envar.

**Comment by wlav** [comment] 2022-12-17 20:02
I do expect that they'd be available b/c otherwise the installation would have failed to begin with (the `CPyCppyy` package needs to be compiled). Perhaps the problem is that the environment isn't propagated into PyCharm?

**Comment by mboker001** [comment] 2022-12-17 20:30
MSVC is apparently  available. Trying now to run Python from visual studio power shell .... looks as if  working better... still facing issues with adding required include path for my dll (for additional header files included in the dll .h file).

**Comment by wlav** [comment] 2023-01-22 06:32
Closing as presumed resolved.

**Closed by wlav** 2023-01-22 06:32 UTC
