### ISSUE TITLE
[regression] enum as argument broken in 2.4.0

### ISSUE THREAD

**Issue by Verma-Rajat** [wlav/cppyy#86] opened 2022-09-05 09:00 UTC
Below code works fine with 2.3.0:

```
import cppyy
cppyy.cppdef("""
typedef enum {
    MONDAY,
    TUESDAY,
    WEDNESDAY
} Day;

void func(const Day day)
{
std::cout << day << std::endl;
}
""")
from cppyy.gbl import Day, WEDNESDAY, func
func(WEDNESDAY)

```

However, on 2.4.0, it throws below error:
```
$ python cppyy_enum.py 
input_line_19:5:26: error: typedef 'Day' cannot be referenced with a enum specifier
   ((void (&)(const enum Day))func)(*(const enum Day*)args[0]);
                         ^
input_line_18:6:3: note: declared here
} Day;
  ^
input_line_19:5:50: error: typedef 'Day' cannot be referenced with a enum specifier
   ((void (&)(const enum Day))func)(*(const enum Day*)args[0]);
                                                 ^
input_line_18:6:3: note: declared here
} Day;
```

**Comment by wlav** [comment] 2022-09-07 20:41
Thanks, I can reproduce. Most probably caused by this: https://github.com/wlav/cppyy-backend/commit/f0d83800c0ee2214c21d0616a14c3b492d9dbe14

**Comment by wlav** [comment] 2023-11-14 23:34
This got fixed somewhere along the way (runs fine with 3.1.1). Closing ...

**Closed by wlav** 2023-11-14 23:34 UTC
